/* Auto-generated by scripts/train-banana-model.py */
#ifndef BANANA_SIGNAL_TOKENS_GENERATED_H
#define BANANA_SIGNAL_TOKENS_GENERATED_H

static const char* const k_banana_signal_tokens_generated[] = {
    "banana",
    "for",
    "baking",
    "bicycle",
    "bottle",
    "bread",
    "ceramic",
    "chips",
    "city",
    "coastal",
    "coffee",
    "compost",
    "counter",
    "crate",
    "dawn",
    "delivered",
    "desk",
    "farm",
    "from",
    "garden",
    "green",
    "harvest",
    "kitchen",
    "lightly",
};

static const unsigned long k_banana_signal_tokens_generated_count =
    sizeof(k_banana_signal_tokens_generated) / sizeof(k_banana_signal_tokens_generated[0]);

#endif /* BANANA_SIGNAL_TOKENS_GENERATED_H */
