import { useEffect, useMemo, useRef, useState } from "react";

/* Emscripten module factory type — generated by MODULARIZE=1 */
type BananaEngineModule = {
  ccall: (name: string, returnType: string, argTypes: string[], args: unknown[]) => unknown;
  cwrap: (name: string, returnType: string, argTypes: string[]) => (...args: unknown[]) => unknown;
};

declare global {
  interface Window {
    BananaEngine?: (config: { canvas: HTMLCanvasElement }) => Promise<BananaEngineModule>;
  }
}

type EngineStatus = "idle" | "loading" | "running" | "error" | "unavailable";

type GeneratedAssetsManifest = {
  seed: number;
  profile: string;
  compiler: string;
  files: string[];
};

type GeneratedTerrain = {
  seed: number;
  width: number;
  height: number;
  algorithm: string;
  cells: Array<{
    tile: string;
    elevation: number;
    resource: number;
  }>;
};

type GeneratedPalette = {
  tiles: Array<{
    id: string;
    biome: number;
    elevationBase: number;
    resourceBias: number;
  }>;
};

function resolveTileColor(tileId: string): string {
  switch (tileId) {
    case "water_deep":
      return "#123a62";
    case "water_shallow":
      return "#1f6f8b";
    case "sand":
      return "#b59b63";
    case "grass":
      return "#4b8b3b";
    case "grove":
      return "#2d6a3b";
    case "hill":
      return "#7d6a4f";
    case "ridge":
      return "#9a8f7a";
    default:
      return "#94a3b8";
  }
}

function shadeColor(hex: string, delta: number): string {
  const normalized = hex.replace("#", "");
  const value = Number.parseInt(normalized, 16);
  const clamp = (channel: number) => Math.max(0, Math.min(255, channel + delta));
  const red = clamp((value >> 16) & 0xff);
  const green = clamp((value >> 8) & 0xff);
  const blue = clamp(value & 0xff);

  return `rgb(${red}, ${green}, ${blue})`;
}

function drawDiamond(
  context: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  topColor: string
) {
  const halfWidth = width / 2;
  const halfHeight = height / 2;

  context.beginPath();
  context.moveTo(x, y - halfHeight);
  context.lineTo(x + halfWidth, y);
  context.lineTo(x, y + halfHeight);
  context.lineTo(x - halfWidth, y);
  context.closePath();
  context.fillStyle = topColor;
  context.fill();

  context.beginPath();
  context.moveTo(x - halfWidth, y);
  context.lineTo(x, y + halfHeight);
  context.lineTo(x, y + halfHeight + 8);
  context.lineTo(x - halfWidth, y + 8);
  context.closePath();
  context.fillStyle = shadeColor(topColor, -30);
  context.fill();

  context.beginPath();
  context.moveTo(x + halfWidth, y);
  context.lineTo(x, y + halfHeight);
  context.lineTo(x, y + halfHeight + 8);
  context.lineTo(x + halfWidth, y + 8);
  context.closePath();
  context.fillStyle = shadeColor(topColor, -55);
  context.fill();
}

export function GameEnginePage() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const assetCanvasRef = useRef<HTMLCanvasElement>(null);
  const moduleRef = useRef<BananaEngineModule | null>(null);
  const rafRef = useRef<number>(0);
  const scriptRef = useRef<HTMLScriptElement | null>(null);

  const [status, setStatus] = useState<EngineStatus>("idle");
  const [error, setError] = useState<string | null>(null);
  const [manifest, setManifest] = useState<GeneratedAssetsManifest | null>(null);
  const [terrain, setTerrain] = useState<GeneratedTerrain | null>(null);
  const [palette, setPalette] = useState<GeneratedPalette | null>(null);
  const [assetError, setAssetError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function loadGeneratedAssets() {
      try {
        const [manifestResponse, terrainResponse, paletteResponse] = await Promise.all([
          fetch("/generated-assets/banana-generated-assets.manifest.json"),
          fetch("/generated-assets/banana-generated-terrain.json"),
          fetch("/generated-assets/banana-generated-palette.json"),
        ]);

        if (!manifestResponse.ok || !terrainResponse.ok || !paletteResponse.ok) {
          throw new Error(
            "Generated assets are unavailable. Run the procedural asset prepare script."
          );
        }

        const [manifestData, terrainData, paletteData] = await Promise.all([
          manifestResponse.json(),
          terrainResponse.json(),
          paletteResponse.json(),
        ]);

        if (!cancelled) {
          setManifest(manifestData as GeneratedAssetsManifest);
          setTerrain(terrainData as GeneratedTerrain);
          setPalette(paletteData as GeneratedPalette);
          setAssetError(null);
        }
      } catch (e) {
        if (!cancelled) {
          setAssetError(e instanceof Error ? e.message : "Unable to load generated assets.");
        }
      }
    }

    void loadGeneratedAssets();

    return () => {
      cancelled = true;
    };
  }, []);

  const assetTiles = useMemo(() => {
    if (!terrain || !palette) {
      return [];
    }

    const tileLookup = new Map(palette.tiles.map((tile) => [tile.id, tile]));
    const sampleStep = terrain.width > 32 ? 2 : 1;
    const sampled = [] as Array<{
      x: number;
      y: number;
      tile: string;
      elevation: number;
      biome: number;
    }>;

    for (let index = 0; index < terrain.cells.length; index += sampleStep) {
      const cell = terrain.cells[index];
      const x = index % terrain.width;
      const y = Math.floor(index / terrain.width);
      const tileMeta = tileLookup.get(cell.tile);

      sampled.push({
        x,
        y,
        tile: cell.tile,
        elevation: cell.elevation,
        biome: tileMeta?.biome ?? 0,
      });
    }

    return sampled;
  }, [palette, terrain]);

  useEffect(() => {
    const assetCanvas = assetCanvasRef.current;
    if (!assetCanvas || assetTiles.length === 0) {
      return;
    }

    const context = assetCanvas.getContext("2d");
    if (!context) {
      return;
    }

    const width = 1280;
    const height = 720;
    assetCanvas.width = width;
    assetCanvas.height = height;
    context.clearRect(0, 0, width, height);

    const gradient = context.createLinearGradient(0, 0, 0, height);
    gradient.addColorStop(0, "rgba(8, 15, 30, 0.15)");
    gradient.addColorStop(1, "rgba(8, 15, 30, 0.55)");
    context.fillStyle = gradient;
    context.fillRect(0, 0, width, height);

    const tileWidth = 34;
    const tileHeight = 18;
    const originX = width / 2;
    const originY = 116;

    for (const tile of assetTiles) {
      const isoX = originX + (tile.x - tile.y) * (tileWidth / 2);
      const isoY = originY + (tile.x + tile.y) * (tileHeight / 2) - tile.elevation * 0.35;
      drawDiamond(context, isoX, isoY, tileWidth, tileHeight, resolveTileColor(tile.tile));
    }
  }, [assetTiles]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    setStatus("loading");

    /* Dynamically load engine.js built by scripts/build-engine-wasm.sh */
    const script = document.createElement("script");
    script.src = "/wasm/engine.js";
    scriptRef.current = script;

    script.onerror = () => {
      setStatus("unavailable");
      setError(
        "engine.js not found. Run: bash scripts/build-engine-wasm.sh (requires Emscripten SDK)"
      );
    };

    script.onload = async () => {
      if (!window.BananaEngine) {
        setStatus("error");
        setError("BananaEngine factory not found after script load");
        return;
      }

      try {
        const mod = await window.BananaEngine({ canvas });
        moduleRef.current = mod;
        setStatus("running");

        const fpsLoop = () => {
          rafRef.current = requestAnimationFrame(fpsLoop);
        };
        rafRef.current = requestAnimationFrame(fpsLoop);
      } catch (e) {
        setStatus("error");
        setError(e instanceof Error ? e.message : "Engine initialization failed");
      }
    };

    document.head.appendChild(script);

    return () => {
      cancelAnimationFrame(rafRef.current);
      scriptRef.current?.remove();
      /* Module shutdown is handled internally by Emscripten on unload */
    };
  }, []);

  return (
    <div className="relative h-[100dvh] min-h-[100svh] w-full overflow-hidden bg-black">
      <div className="absolute inset-0 z-0 bg-[radial-gradient(circle_at_top,_rgba(34,211,238,0.10),_transparent_40%),linear-gradient(180deg,_rgba(2,6,23,0.25),_rgba(2,6,23,0.75))]" />
      <canvas
        ref={canvasRef}
        id="canvas"
        width={1280}
        height={720}
        className="absolute inset-0 z-10 h-full w-full object-contain"
        style={{ imageRendering: "pixelated", objectPosition: "center" }}
      />
      <canvas
        ref={assetCanvasRef}
        aria-hidden="true"
        width={1280}
        height={720}
        className="pointer-events-none absolute inset-0 z-20 hidden h-full w-full object-contain opacity-45 mix-blend-screen md:block"
        style={{ objectPosition: "center" }}
      />
      {(status === "loading" || !terrain || !palette) && !error && !assetError && (
        <div className="pointer-events-none absolute inset-0 z-30 bg-[radial-gradient(circle_at_center,_rgba(15,23,42,0.08),_rgba(2,6,23,0.32))]" />
      )}
      {(status === "error" || status === "unavailable" || assetError) && (
        <div className="absolute bottom-4 left-4 z-40 max-w-md rounded-md border border-red-400/30 bg-slate-950/80 px-4 py-3 text-sm text-red-200 backdrop-blur">
          {assetError ?? error}
        </div>
      )}
    </div>
  );
}
