import { useEffect, useRef, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { GameWorldMap, type EntitySnapshot } from "../components/GameWorldMap";
import { GameTelemetry, type TelemetrySnapshot } from "../components/GameTelemetry";

/* Emscripten module factory type — generated by MODULARIZE=1 */
type BananaEngineModule = {
  ccall: (name: string, returnType: string, argTypes: string[], args: unknown[]) => unknown;
  cwrap: (name: string, returnType: string, argTypes: string[]) => (...args: unknown[]) => unknown;
  _engine_get_entity_count?: () => number;
  _engine_get_entity_x?: (idx: number) => number;
  _engine_get_entity_z?: (idx: number) => number;
  _engine_get_entity_state?: (idx: number) => number;
};

declare global {
  interface Window {
    BananaEngine?: (config: { canvas: HTMLCanvasElement }) => Promise<BananaEngineModule>;
  }
}

type EngineStatus = "idle" | "loading" | "running" | "error" | "unavailable";

function StatusBadge({ status }: { status: EngineStatus }) {
  const colors: Record<EngineStatus, string> = {
    idle: "bg-secondary text-secondary-foreground",
    loading: "bg-yellow-100 text-yellow-800",
    running: "bg-green-100 text-green-800",
    error: "bg-red-100 text-red-800",
    unavailable: "bg-secondary text-muted-foreground",
  };
  return (
    <span className={`rounded-full px-3 py-1 text-xs font-medium ${colors[status]}`}>{status}</span>
  );
}

export function GameEnginePage() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const moduleRef = useRef<BananaEngineModule | null>(null);
  const rafRef = useRef<number>(0);
  const scriptRef = useRef<HTMLScriptElement | null>(null);

  const [status, setStatus] = useState<EngineStatus>("idle");
  const [frameCount, setFrameCount] = useState(0);
  const [fps, setFps] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [entities, setEntities] = useState<EntitySnapshot[]>([]);
  const [telemetry, setTelemetry] = useState<TelemetrySnapshot>({
    fps: 0,
    frameCount: 0,
    entityCount: 0,
    frameTimes: [],
  });

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    setStatus("loading");

    /* Dynamically load engine.js built by scripts/build-engine-wasm.sh */
    const script = document.createElement("script");
    script.src = "/wasm/engine.js";
    scriptRef.current = script;

    script.onerror = () => {
      setStatus("unavailable");
      setError(
        "engine.js not found. Run: bash scripts/build-engine-wasm.sh (requires Emscripten SDK)"
      );
    };

    script.onload = async () => {
      if (!window.BananaEngine) {
        setStatus("error");
        setError("BananaEngine factory not found after script load");
        return;
      }

      try {
        const mod = await window.BananaEngine({ canvas });
        moduleRef.current = mod;
        setStatus("running");

        /* Track FPS + poll entity positions + frame times */
        let frames = 0;
        let lastFpsTime = performance.now();
        let lastFrameTime = performance.now();
        const frameTimesRing: number[] = [];

        const fpsLoop = () => {
          frames++;
          const now = performance.now();
          const dt = now - lastFrameTime;
          lastFrameTime = now;

          /* Rolling 300-sample frame-time ring buffer */
          frameTimesRing.push(dt);
          if (frameTimesRing.length > 300) frameTimesRing.shift();

          /* Update entity positions every frame (cheap WASM int reads) */
          if (mod._engine_get_entity_count) {
            const count = mod._engine_get_entity_count();
            const snaps: EntitySnapshot[] = [];
            for (let i = 0; i < count; i++) {
              snaps.push({
                idx: i,
                x: mod._engine_get_entity_x ? mod._engine_get_entity_x(i) : 0,
                z: mod._engine_get_entity_z ? mod._engine_get_entity_z(i) : 0,
                state: mod._engine_get_entity_state ? mod._engine_get_entity_state(i) : 0,
              });
            }
            setEntities(snaps);
          }

          if (now - lastFpsTime >= 1000) {
            const currentFps = frames;
            setFps(currentFps);
            setFrameCount((c) => c + frames);
            setTelemetry({
              fps: currentFps,
              frameCount: 0 /* absolute count updated separately */,
              entityCount: entities.length,
              frameTimes: [...frameTimesRing],
            });
            frames = 0;
            lastFpsTime = now;
          }

          rafRef.current = requestAnimationFrame(fpsLoop);
        };
        rafRef.current = requestAnimationFrame(fpsLoop);
      } catch (e) {
        setStatus("error");
        setError(e instanceof Error ? e.message : "Engine initialization failed");
      }
    };

    document.head.appendChild(script);

    return () => {
      cancelAnimationFrame(rafRef.current);
      scriptRef.current?.remove();
      /* Module shutdown is handled internally by Emscripten on unload */
    };
  }, []);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold">Game Engine</h2>
          <p className="text-sm text-muted-foreground">
            C-native open world engine — compiled to WebAssembly
          </p>
        </div>
        <div className="flex items-center gap-3">
          <StatusBadge status={status} />
          {status === "running" && (
            <span className="text-xs text-muted-foreground">
              {fps} fps · {frameCount} frames
            </span>
          )}
        </div>
      </div>

      {/* Canvas */}
      <div className="overflow-hidden rounded-lg border bg-black">
        <canvas
          ref={canvasRef}
          id="canvas"
          width={800}
          height={600}
          className="block w-full"
          style={{ imageRendering: "pixelated" }}
        />
      </div>

      {/* Error / Setup instructions */}
      {status === "unavailable" && (
        <Card>
          <CardHeader>
            <CardTitle className="text-sm">Engine WASM not built yet</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm text-muted-foreground">
            <p>{error}</p>
            <ol className="list-decimal list-inside space-y-1">
              <li>
                Install Emscripten SDK:{" "}
                <code>git clone https://github.com/emscripten-core/emsdk.git</code>
              </li>
              <li>
                Activate:{" "}
                <code>
                  cd emsdk && ./emsdk install latest && ./emsdk activate latest && source
                  ./emsdk_env.sh
                </code>
              </li>
              <li>
                Build engine: <code>bash scripts/build-engine-wasm.sh</code>
              </li>
              <li>Restart the React dev server and reload this page</li>
            </ol>
          </CardContent>
        </Card>
      )}

      {status === "error" && (
        <Card className="border-destructive">
          <CardContent className="pt-4 text-sm text-destructive">{error}</CardContent>
        </Card>
      )}

      {/* Info panel + live data */}
      {status === "running" && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            {/* World map */}
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">World Map</CardTitle>
              </CardHeader>
              <CardContent className="flex justify-center">
                <GameWorldMap entities={entities} worldSize={30} width={220} height={220} />
              </CardContent>
            </Card>

            {/* Telemetry */}
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">Performance</CardTitle>
              </CardHeader>
              <CardContent>
                <GameTelemetry data={{ ...telemetry, frameCount, fps }} />
              </CardContent>
            </Card>
          </div>

          {/* Engine info cards */}
          <div className="grid grid-cols-3 gap-3 text-sm">
            <Card>
              <CardContent className="pt-4">
                <p className="text-muted-foreground text-xs">Renderer</p>
                <p className="font-medium">WebGL 2 (GLES 3.0)</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="pt-4">
                <p className="text-muted-foreground text-xs">AI Controllers</p>
                <p className="font-medium">{entities.length} × Wildlife NPC</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="pt-4">
                <p className="text-muted-foreground text-xs">Physics</p>
                <p className="font-medium">Rigid body, 60 Hz</p>
              </CardContent>
            </Card>
          </div>
        </div>
      )}
    </div>
  );
}
