/* Auto-generated by scripts/train-ripeness-model.py */
#ifndef BANANA_RIPENESS_LABELS_GENERATED_H
#define BANANA_RIPENESS_LABELS_GENERATED_H

static const char* const k_banana_ripeness_labels_generated[] = {
    "unripe",
    "ripe",
    "overripe",
    "spoiled",
};

static const unsigned long k_banana_ripeness_labels_generated_count =
    sizeof(k_banana_ripeness_labels_generated) / sizeof(k_banana_ripeness_labels_generated[0]);

#endif /* BANANA_RIPENESS_LABELS_GENERATED_H */
