// Slice 026 -- snapshot lock on generated web.css.
// Asserts the generator output matches the committed file. Drift in
// either direction (forgot to regenerate, or hand-edited web.css)
// trips this test.

import { expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import { tokens } from "./src/tokens";

test("tokens object exposes the SPIKE 021 contract surface", () => {
  expect(tokens.color.banana.bg).toBe("#fef3c7");
  expect(tokens.color.notbanana.bg).toBe("#e2e8f0");
  expect(tokens.color.escalation.fg).toBe("#92400e");
  expect(tokens.color.text.error).toBe("#b91c1c");
  expect(tokens.font.size.md).toBe(16);
  expect(tokens.font.weight.semibold).toBe("600");
  expect(tokens.space[4]).toBe(16);
  expect(tokens.radius.md).toBe(8);
  expect(tokens.motion.medium).toBe("240ms");
});

test("generated web.css matches the committed snapshot", () => {
  const cssPath = resolve(import.meta.dir, "src", "tokens", "web.css");
  expect(existsSync(cssPath)).toBe(true);
  const css = readFileSync(cssPath, "utf8");
  // Banner + a representative slice of the contract.
  expect(css).toContain("/* Generated by scripts/generate-web-tokens.ts.");
  expect(css).toContain("--color-banana-bg: #fef3c7;");
  expect(css).toContain("--color-notbanana-bg: #e2e8f0;");
  expect(css).toContain("--color-escalation-fg: #92400e;");
  expect(css).toContain("--color-text-error: #b91c1c;");
  expect(css).toContain("--font-size-md: 16px;");
  expect(css).toContain("--font-weight-semibold: 600;");
  expect(css).toContain("--space-4: 16px;");
  expect(css).toContain("--radius-md: 8px;");
  expect(css).toContain("--motion-medium: 240ms;");
});
