#!/usr/bin/env python3
"""Render a deterministic SDLC plan from a base catalog and native C model lanes."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build deterministic autonomous SDLC plan from native model output."
    )
    parser.add_argument(
        "--catalog", required=True, help="Path to base increment catalog JSON"
    )
    parser.add_argument(
        "--model-json", required=True, help="Path to deterministic native model JSON"
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output path for rendered deterministic plan JSON",
    )
    return parser.parse_args()


def sanitize_slug(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9._-]+", "-", value.strip().lower()).strip("-._")
    return normalized or "increment"


def extract_agent_label(labels: str) -> str | None:
    for raw_label in labels.split(","):
        label = raw_label.strip()
        if label.startswith("agent:"):
            return label.split(":", 1)[1].strip()
    return None


def ensure_label_set(labels: str, agent_slug: str) -> str:
    existing = [item.strip() for item in labels.split(",") if item.strip()]
    normalized = {item.lower() for item in existing}

    required = [
        "automation",
        "sdlc",
        "triaged-item",
        "copilot-auto-approve",
        "copilot-autonomous-cycle",
        "speckit-driven",
        f"agent:{agent_slug}",
    ]

    for label in required:
        if label.lower() not in normalized:
            existing.append(label)
            normalized.add(label.lower())

    return ",".join(existing)


def clone_increment(entry: dict[str, Any], agent_slug: str) -> dict[str, Any]:
    clone = dict(entry)
    clone["labels"] = ensure_label_set(str(clone.get("labels", "")), agent_slug)
    return clone


def unique_increment_id(preferred: str, seen: set[str]) -> str:
    base = sanitize_slug(preferred)
    candidate = base
    suffix = 2

    while candidate in seen:
        candidate = f"{base}-{suffix}"
        suffix += 1

    seen.add(candidate)
    return candidate


def build_synthetic_increment(
    agent_slug: str, focus: str, sequence: int, seen_ids: set[str]
) -> dict[str, Any]:
    increment_id = unique_increment_id(f"pulse-{agent_slug}-{sequence}", seen_ids)
    slug = sanitize_slug(agent_slug.replace("-agent", ""))
    intent = f"Deterministic native model pulse {sequence} for {focus}."

    return {
        "id": increment_id,
        "change_command": (
            "python scripts/record-agent-pulse-activity.py "
            f"--agent {agent_slug} "
            f"--increment-id {increment_id} "
            f'--intent "{intent}"'
        ),
        "commit_message": f"chore({slug}): deterministic pulse snapshot {sequence}",
        "pr_title": f"triage({slug}): deterministic pulse snapshot {sequence}",
        "pr_body": (
            "Autonomous self-training increment generated by native deterministic model: "
            f"pulse {sequence} for {agent_slug} ({focus})."
        ),
        "labels": ensure_label_set("", agent_slug),
    }


def main() -> int:
    args = parse_args()
    catalog_path = pathlib.Path(args.catalog)
    model_path = pathlib.Path(args.model_json)
    output_path = pathlib.Path(args.output)

    catalog_raw = json.loads(catalog_path.read_text(encoding="utf-8"))
    model_raw = json.loads(model_path.read_text(encoding="utf-8"))

    if not isinstance(catalog_raw, list):
        raise SystemExit("Catalog JSON must be an array of increment objects.")

    lanes = model_raw.get("lanes", [])
    if not isinstance(lanes, list) or not lanes:
        raise SystemExit("Native model JSON must provide a non-empty 'lanes' array.")

    increments_by_agent: dict[str, list[dict[str, Any]]] = {}
    unowned_increments: list[dict[str, Any]] = []

    for raw_entry in catalog_raw:
        if not isinstance(raw_entry, dict):
            raise SystemExit("Catalog entries must be JSON objects.")

        labels = str(raw_entry.get("labels", ""))
        agent_slug = extract_agent_label(labels)
        if agent_slug:
            increments_by_agent.setdefault(agent_slug, []).append(raw_entry)
        else:
            unowned_increments.append(raw_entry)

    rendered: list[dict[str, Any]] = []
    seen_ids: set[str] = set()

    for lane in lanes:
        if not isinstance(lane, dict):
            raise SystemExit("Lane entries in model JSON must be objects.")

        agent_slug = sanitize_slug(str(lane.get("agent", "")))
        focus = str(lane.get("focus", "management-lane")).strip() or "management-lane"
        snapshots = int(lane.get("deterministic_snapshots", 1))
        if snapshots < 1:
            snapshots = 1

        base_entries = sorted(
            increments_by_agent.get(agent_slug, []),
            key=lambda item: str(item.get("id", "")),
        )

        for base_entry in base_entries:
            clone = clone_increment(base_entry, agent_slug)
            clone["id"] = unique_increment_id(
                str(clone.get("id", agent_slug)), seen_ids
            )
            rendered.append(clone)

        base_count = len(base_entries)
        synthetic_start = base_count + 1
        for sequence in range(synthetic_start, snapshots + 1):
            rendered.append(
                build_synthetic_increment(agent_slug, focus, sequence, seen_ids)
            )

    for leftover_agent, leftover_entries in sorted(increments_by_agent.items()):
        if any(
            sanitize_slug(leftover_agent) == sanitize_slug(str(lane.get("agent", "")))
            for lane in lanes
        ):
            continue

        for leftover_entry in sorted(
            leftover_entries, key=lambda item: str(item.get("id", ""))
        ):
            clone = clone_increment(leftover_entry, leftover_agent)
            clone["id"] = unique_increment_id(
                str(clone.get("id", leftover_agent)), seen_ids
            )
            rendered.append(clone)

    for entry in unowned_increments:
        clone = dict(entry)
        clone["id"] = unique_increment_id(
            str(clone.get("id", "unowned-increment")), seen_ids
        )
        rendered.append(clone)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(rendered, indent=2) + "\n", encoding="utf-8")
    print(str(output_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
