#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_ID="${GITHUB_RUN_ID:-local-run}"
RUN_ATTEMPT="${GITHUB_RUN_ATTEMPT:-1}"

TRIAGE_IDEA="${BANANA_TRIAGE_IDEA:-}"
TRIAGE_ISSUE_NUMBER="${BANANA_TRIAGE_ISSUE_NUMBER:-}"
TRIAGE_ISSUE_LABELS="${BANANA_TRIAGE_ISSUE_LABELS:-triage-idea,copilot-suggestion,automation,copilot-bypass-vibe-coded}"
TRIAGE_PR_LABELS="${BANANA_TRIAGE_PR_LABELS:-automation,triaged-item,copilot-auto-approve,copilot-autonomous-cycle,copilot-bypass-vibe-coded}"
TRIAGE_INTAKE_DIR="${BANANA_TRIAGE_INTAKE_DIR:-docs/triage/intake}"
BASE_BRANCH="${BANANA_BASE_BRANCH:-main}"
BRANCH_PREFIX="${BANANA_BRANCH_PREFIX:-triage}"
DRAFT_PR="${BANANA_DRAFT_PR:-false}"
TRIAGE_DISPATCH_REQUIRED_CHECKS="${BANANA_TRIAGE_DISPATCH_REQUIRED_CHECKS:-true}"
TRIAGE_CHECK_WORKFLOWS="${BANANA_TRIAGE_CHECK_WORKFLOWS:-copilot-review-triage.yml,require-human-approval.yml}"
PR_REVIEWERS="${BANANA_PR_REVIEWERS:-}"
SKIP_IF_NO_CHANGES="${BANANA_SKIP_IF_NO_CHANGES:-true}"
PR_OUTPUT_PATH="${BANANA_PR_OUTPUT_PATH:-artifacts/triage-idea/triage-pr-output-${RUN_ID}-attempt-${RUN_ATTEMPT}.json}"

mkdir -p "$(dirname "$PR_OUTPUT_PATH")"

if ! command -v gh >/dev/null 2>&1; then
  echo "::error::GitHub CLI is required to orchestrate triage ideas in cloud workflows."
  exit 1
fi

parse_list_input() {
  local raw="${1:-}"
  local -n out_items="$2"
  local normalized
  local item
  local -a raw_items=()

  normalized="${raw//$'\r'/}"
  normalized="${normalized//$'\n'/,}"
  normalized="$(echo "$normalized" | xargs)"

  if [[ -z "$normalized" ]]; then
    return 0
  fi

  if [[ "$normalized" == \[*\] ]]; then
    normalized="${normalized#[}"
    normalized="${normalized%]}"
  fi

  IFS=',' read -r -a raw_items <<< "$normalized"
  for raw_item in "${raw_items[@]}"; do
    item="$(echo "$raw_item" | xargs)"
    item="${item#\"}"
    item="${item%\"}"
    item="${item#\'}"
    item="${item%\'}"
    item="$(echo "$item" | xargs)"
    if [[ -n "$item" ]]; then
      out_items+=("$item")
    fi
  done
}

normalize_whitespace() {
  local raw="${1:-}"
  printf '%s' "$raw" | tr '\r\n' '  ' | sed -E 's/[[:space:]]+/ /g' | xargs
}

get_repo_slug() {
  if [[ -n "${GITHUB_REPOSITORY:-}" ]]; then
    printf '%s' "$GITHUB_REPOSITORY"
    return 0
  fi

  gh repo view --json nameWithOwner -q .nameWithOwner
}

dispatch_gate_workflow() {
  local repo_slug="$1"
  local workflow_file="$2"
  local pr_number="$3"
  local pr_branch="$4"

  if [[ -z "$workflow_file" ]]; then
    return 0
  fi

  if gh api -X POST "repos/${repo_slug}/actions/workflows/${workflow_file}/dispatches" \
    -f ref="$pr_branch" \
    -f inputs[pull_number]="$pr_number" >/dev/null 2>&1; then
    echo "Dispatched gate workflow '${workflow_file}' for PR #${pr_number} (${pr_branch})."
    return 0
  fi

  echo "::warning::Unable to dispatch gate workflow '${workflow_file}' for PR #${pr_number}."
  return 1
}

ensure_label() {
  local label_name="$1"
  local color="$2"
  local description="$3"

  if ! gh label create "$label_name" --color "$color" --description "$description" >/dev/null 2>&1; then
    gh label edit "$label_name" --color "$color" --description "$description" >/dev/null 2>&1 || true
  fi
}

ensure_issue_label_contract() {
  ensure_label "triage-idea" "FBCA04" "Idea queued for cloud triage orchestration"
  ensure_label "copilot-suggestion" "C5DEF5" "Copilot review suggestion triaged into issue backlog"
  ensure_label "copilot-bypass-vibe-coded" "0B63A5" "Bypass human gate after Copilot triage while tracking vibe-coded integrations"
}

apply_issue_labels() {
  local issue_number="$1"
  local -n labels_ref="$2"

  for label in "${labels_ref[@]}"; do
    if gh issue edit "$issue_number" --add-label "$label" >/dev/null 2>&1; then
      continue
    fi

    if [[ "$label" == "triage-idea" || "$label" == "copilot-suggestion" ]]; then
      ensure_issue_label_contract
      gh issue edit "$issue_number" --add-label "$label" >/dev/null 2>&1 || true
      continue
    fi

    echo "::warning::Unable to add label '$label' to issue #$issue_number."
  done
}

ensure_issue_label_contract

declare -a parsed_issue_labels=()
parse_list_input "$TRIAGE_ISSUE_LABELS" parsed_issue_labels

if [[ -z "$TRIAGE_ISSUE_NUMBER" ]]; then
  normalized_idea="$(normalize_whitespace "$TRIAGE_IDEA")"

  if [[ -z "$normalized_idea" ]]; then
    echo "::error::Provide BANANA_TRIAGE_IDEA when BANANA_TRIAGE_ISSUE_NUMBER is not set."
    exit 1
  fi

  issue_title="${BANANA_TRIAGE_ISSUE_TITLE:-triage: ${normalized_idea}}"
  if [[ ${#issue_title} -gt 120 ]]; then
    issue_title="${issue_title:0:117}..."
  fi

  issue_body_default=$(cat <<EOF
## Idea

${TRIAGE_IDEA}

## Requested automation

- Capture this idea in ${TRIAGE_INTAKE_DIR}.
- Open an automation pull request via triaged-item orchestration.
- Preserve Copilot provenance labels for downstream automation review.

_This issue was generated by cloud triage orchestration._
EOF
)
  issue_body="${BANANA_TRIAGE_ISSUE_BODY:-$issue_body_default}"

  issue_url="$(gh issue create --title "$issue_title" --body "$issue_body")"
  TRIAGE_ISSUE_NUMBER="${issue_url##*/}"
fi

apply_issue_labels "$TRIAGE_ISSUE_NUMBER" parsed_issue_labels

issue_title="$(gh issue view "$TRIAGE_ISSUE_NUMBER" --json title --jq .title)"
issue_url="$(gh issue view "$TRIAGE_ISSUE_NUMBER" --json url --jq .url)"
issue_body="$(gh issue view "$TRIAGE_ISSUE_NUMBER" --json body --jq .body)"
if [[ "$issue_body" == "null" ]]; then
  issue_body=""
fi

issue_labels_multiline="$(gh issue view "$TRIAGE_ISSUE_NUMBER" --json labels --jq '.labels[].name' || true)"
if [[ -n "$issue_labels_multiline" ]]; then
  issue_labels_csv="$(printf '%s\n' "$issue_labels_multiline" | paste -sd ',' -)"
else
  issue_labels_csv=""
fi

issue_slug="$(printf '%s' "$issue_title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+//; s/-+$//')"
if [[ -z "$issue_slug" ]]; then
  issue_slug="triage-idea"
fi
issue_slug="${issue_slug:0:48}"
triage_id="issue-${TRIAGE_ISSUE_NUMBER}-${issue_slug}"
triage_id="${triage_id:0:96}"

intake_file="${TRIAGE_INTAKE_DIR}/issue-${TRIAGE_ISSUE_NUMBER}.md"
mkdir -p "$TRIAGE_INTAKE_DIR"

cat > "$intake_file" <<EOF
# Triage Intake: Issue #${TRIAGE_ISSUE_NUMBER}

- Source issue: ${issue_url}
- Source title: ${issue_title}
- Source labels: ${issue_labels_csv}

## Idea

${issue_body}

## Cloud Orchestration Contract

- Entry workflow: Orchestrate Triage Idea Cloud
- Pull request labels: ${TRIAGE_PR_LABELS}
- Base branch: ${BASE_BRANCH}
- Branch prefix: ${BRANCH_PREFIX}
EOF

title_summary="$(normalize_whitespace "$issue_title")"
if [[ ${#title_summary} -gt 72 ]]; then
  title_summary="${title_summary:0:69}..."
fi

pr_body_default=$(cat <<EOF
Cloud triage intake generated from issue #${TRIAGE_ISSUE_NUMBER}.

- Source issue: ${issue_url}
- Intake artifact: ${intake_file}
- Workflow run: ${RUN_ID} attempt ${RUN_ATTEMPT}
EOF
)

export BANANA_TRIAGE_ID="$triage_id"
export BANANA_TRIAGE_CHANGE_COMMAND=":"
export BANANA_BASE_BRANCH="$BASE_BRANCH"
export BANANA_BRANCH_PREFIX="$BRANCH_PREFIX"
export BANANA_COMMIT_MESSAGE="${BANANA_COMMIT_MESSAGE:-chore(triage): intake issue #${TRIAGE_ISSUE_NUMBER}}"
export BANANA_PR_TITLE="${BANANA_PR_TITLE:-triage(issue-${TRIAGE_ISSUE_NUMBER}): intake ${title_summary}}"
export BANANA_PR_BODY="${BANANA_PR_BODY:-$pr_body_default}"
export BANANA_DRAFT_PR="$DRAFT_PR"
export BANANA_PR_LABELS="$TRIAGE_PR_LABELS"
export BANANA_PR_REVIEWERS="$PR_REVIEWERS"
export BANANA_SKIP_IF_NO_CHANGES="$SKIP_IF_NO_CHANGES"
export BANANA_PR_OUTPUT_PATH="$PR_OUTPUT_PATH"

bash scripts/workflow-orchestrate-triaged-item-pr.sh

pr_status="$(python - "$PR_OUTPUT_PATH" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
if not path.exists():
    print("")
    raise SystemExit(0)

payload = json.loads(path.read_text(encoding="utf-8"))
print(payload.get("status", ""))
PY
)"

pr_url="$(python - "$PR_OUTPUT_PATH" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
if not path.exists():
    print("")
    raise SystemExit(0)

payload = json.loads(path.read_text(encoding="utf-8"))
print(payload.get("pr_url", ""))
PY
)"

pr_number="$(python - "$PR_OUTPUT_PATH" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
if not path.exists():
    print("")
    raise SystemExit(0)

payload = json.loads(path.read_text(encoding="utf-8"))
print(payload.get("pr_number", ""))
PY
)"

pr_branch="$(python - "$PR_OUTPUT_PATH" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
if not path.exists():
    print("")
    raise SystemExit(0)

payload = json.loads(path.read_text(encoding="utf-8"))
print(payload.get("branch", ""))
PY
)"

if [[ "$TRIAGE_DISPATCH_REQUIRED_CHECKS" == "true" && "$pr_status" == "created" && -n "$pr_number" && -n "$pr_branch" ]]; then
  repo_slug="$(get_repo_slug)"

  declare -a parsed_check_workflows=()
  parse_list_input "$TRIAGE_CHECK_WORKFLOWS" parsed_check_workflows
  for workflow_file in "${parsed_check_workflows[@]}"; do
    dispatch_gate_workflow "$repo_slug" "$workflow_file" "$pr_number" "$pr_branch" || true
  done
fi

if [[ -n "$pr_url" ]]; then
  gh issue comment "$TRIAGE_ISSUE_NUMBER" --body "Automation PR opened for this triage idea: ${pr_url}" >/dev/null 2>&1 || true
elif [[ "$pr_status" == "skipped" ]]; then
  gh issue comment "$TRIAGE_ISSUE_NUMBER" --body "Cloud triage orchestration found no effective repository change and skipped PR creation." >/dev/null 2>&1 || true
fi

if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  {
    echo "issue_number=${TRIAGE_ISSUE_NUMBER}"
    echo "issue_url=${issue_url}"
    echo "triage_id=${triage_id}"
    echo "pr_status=${pr_status}"
    echo "pr_url=${pr_url}"
    echo "pr_output_path=${PR_OUTPUT_PATH}"
  } >> "$GITHUB_OUTPUT"
fi

echo "Triage idea orchestration complete for issue #${TRIAGE_ISSUE_NUMBER}."
