/* Auto-generated by scripts/train-not-banana-model.py.
 * Do not edit by hand. Re-run the trainer to refresh this file.
 * Generated from data/not-banana/corpus.json.
 */
#ifndef BANANA_NOT_BANANA_GENERATED_VOCABULARY_H
#define BANANA_NOT_BANANA_GENERATED_VOCABULARY_H

static const char* const k_banana_signal_tokens_generated[] = {
    "banana",
    "variety",
    "b",
    "cavendish",
    "harvest",
    "peel",
    "plantain",
    "ripeness",
    "ripening",
    "yellow",
    "bn",
    "bunch",
    "fruit",
    "shipment",
    "spotted",
    "0.4",
    "0.6",
    "1.2",
    "101",
    "12",
    "21",
    "7",
    "acuminata",
    "advanced",
    "at",
    "bananabatch",
    "bananabunch",
    "batch",
    "bb",
    "breaking",
    "complete",
    "day",
};

static const int k_banana_signal_token_count_generated =
    (int)(sizeof(k_banana_signal_tokens_generated) / sizeof(k_banana_signal_tokens_generated[0]));

#endif
