import {
  ContextMenu,
  type ContextMenuAction,
  type ContextMenuState,
  ControlsHint,
  type EngineStatus,
  EngineVersionBadge,
  ErrorBadge,
  GameEngineUIService,
  type GameEngineUIState,
  getDirectionFromTouch,
  InteractionMessageBadge,
  isMovementKey,
  MobileRadialControl,
  NetcodeDomain,
  type RadialControlState,
  ReplicationDomain,
  SplashOverlay,
  ViewportErrorOverlay,
} from "@banana/ui";
import { useEffect, useLayoutEffect, useRef, useState } from "react";

/* Emscripten module factory type — generated by MODULARIZE=1 */
type BananaEngineModule = {
  ccall: (name: string, returnType: string, argTypes: string[], args: unknown[]) => unknown;
  cwrap: (name: string, returnType: string, argTypes: string[]) => (...args: unknown[]) => unknown;
};

function isWebGL2Available(): boolean {
  try {
    const probeCanvas = document.createElement("canvas");
    const context = probeCanvas.getContext("webgl2");
    return context !== null;
  } catch {
    return false;
  }
}

declare global {
  interface Window {
    BananaEngine?: (config: {
      canvas: HTMLCanvasElement;
      locateFile?: (path: string, prefix: string) => string;
      printErr?: (text: string) => void;
      onAbort?: (reason: string) => void;
    }) => Promise<BananaEngineModule>;
    __bananaEngineModule?: BananaEngineModule;
  }
}

const CONTEXT_MENU_ACTIONS: ContextMenuAction[] = [
  { label: "Interact", actionId: "interact" },
  { label: "Harvest", actionId: "harvest" },
];

/* Asset rendering now fully handled by C/WASM engine */

/**
 * GameEnginePage — Pure C/WASM viewport
 *
 * React serves as a minimal container only. All viewport sizing, scaling,
 * and responsive behavior is handled directly by the WASM engine from C code.
 * No Tailwind/CSS styling constraints on the primary canvas.
 *
 * Future: HUD overlays (menu, status, controls) scaffold separately if needed.
 */
export function GameEnginePage() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const viewportRef = useRef<HTMLDivElement>(null);
  const moduleRef = useRef<BananaEngineModule | null>(null);
  const intervalRef = useRef<number>(0);
  const scriptRef = useRef<HTMLScriptElement | null>(null);
  const netcodeRef = useRef<NetcodeDomain | null>(null);
  const replicationRef = useRef<ReplicationDomain | null>(null);

  /* GameEngineUIService manages all UI state (Phase 2 integration) */
  const uiServiceRef = useRef<GameEngineUIService | null>(null);
  const keyDownHandlerRef = useRef<((event: KeyboardEvent) => void) | null>(null);
  const keyUpHandlerRef = useRef<((event: KeyboardEvent) => void) | null>(null);
  const blurHandlerRef = useRef<(() => void) | null>(null);
  const visibilityHandlerRef = useRef<(() => void) | null>(null);
  const touchStartHandlerRef = useRef<((event: TouchEvent) => void) | null>(null);
  const touchMoveHandlerRef = useRef<((event: TouchEvent) => void) | null>(null);
  const touchEndHandlerRef = useRef<((event: TouchEvent) => void) | null>(null);
  const pointerDownHandlerRef = useRef<((event: PointerEvent) => void) | null>(null);
  const pointerMoveHandlerRef = useRef<((event: PointerEvent) => void) | null>(null);
  const pointerUpHandlerRef = useRef<((event: PointerEvent) => void) | null>(null);
  const activePointerIdRef = useRef<number | null>(null);
  const touchStartTimerRef = useRef<number>(0);
  const renderHealthTimerRef = useRef<number>(0);
  const activeTouchIdRef = useRef<number | null>(null);

  /* React state subscribed from GameEngineUIService */
  const [status, setStatus] = useState<EngineStatus>("idle");
  const [error, setError] = useState<string | null>(null);
  const [contextMenu, setContextMenu] = useState<ContextMenuState>({
    visible: false,
    x: 0,
    y: 0,
    normalizedX: 0,
    normalizedY: 0,
  });
  const [radialControl, setRadialControl] = useState<RadialControlState>({
    visible: false,
    x: 0,
    y: 0,
    activeDirection: null,
  });
  const [interactionMessage, setInteractionMessage] = useState<string | null>(null);
  const [engineAssetVersion, setEngineAssetVersion] = useState<string>("pending");

  useLayoutEffect(() => {
    const canvas = canvasRef.current;
    const viewport = viewportRef.current;
    if (!canvas || !viewport) return;

    // Native WASM window path resolves the target by #canvas.
    // biome-ignore lint: useUniqueElementIds: Emscripten native code hardcodes #canvas.
    canvas.id = "canvas";

    const resolveViewportSize = () => {
      const bounds = viewport.getBoundingClientRect();
      const visualViewport = window.visualViewport;

      // On some mobile browsers during chrome/url-bar transitions, fixed containers
      // can briefly report 0x0. Fall back to visualViewport/window dimensions.
      const cssWidth = Math.max(
        1,
        Math.floor(
          (bounds.width > 1 ? bounds.width : 0) ||
          visualViewport?.width ||
          window.innerWidth ||
          document.documentElement.clientWidth ||
          1
        )
      );
      const cssHeight = Math.max(
        1,
        Math.floor(
          (bounds.height > 1 ? bounds.height : 0) ||
          visualViewport?.height ||
          window.innerHeight ||
          document.documentElement.clientHeight ||
          1
        )
      );

      return { cssWidth, cssHeight };
    };

    const syncCanvasCssSize = () => {
      const { cssWidth, cssHeight } = resolveViewportSize();
      const dpr = Math.max(1, window.devicePixelRatio || 1);
      const pixelWidth = Math.max(1, Math.floor(cssWidth * dpr));
      const pixelHeight = Math.max(1, Math.floor(cssHeight * dpr));
      canvas.style.width = `${cssWidth}px`;
      canvas.style.height = `${cssHeight}px`;
      if (canvas.width !== pixelWidth) {
        canvas.width = pixelWidth;
      }
      if (canvas.height !== pixelHeight) {
        canvas.height = pixelHeight;
      }

      uiServiceRef.current?.checkViewportChange();
    };

    syncCanvasCssSize();

    const observer = new ResizeObserver(() => {
      syncCanvasCssSize();
    });
    observer.observe(viewport);

    window.addEventListener("resize", syncCanvasCssSize);
    window.visualViewport?.addEventListener("resize", syncCanvasCssSize);
    return () => {
      observer.disconnect();
      window.removeEventListener("resize", syncCanvasCssSize);
      window.visualViewport?.removeEventListener("resize", syncCanvasCssSize);
    };
  }, []);

  useEffect(() => {
    const env = (import.meta as { env?: Record<string, unknown> }).env;
    const isDev = Boolean(env?.DEV);
    if (!isDev) return;
    if (window.location.hostname === "app.example") return;

    let lastVersion: string | null = null;
    const pollForWasmChanges = async () => {
      try {
        const response = await fetch(`/wasm/engine.version.json?dev-watch=${Date.now()}`, {
          cache: "no-store",
        });
        if (!response.ok) return;

        const payload = (await response.json()) as { engineAssetVersion?: string };
        const currentVersion = payload.engineAssetVersion;
        if (!currentVersion) return;

        if (lastVersion === null) {
          lastVersion = currentVersion;
          return;
        }

        if (currentVersion !== lastVersion) {
          window.location.reload();
        }
      } catch {
        /* best-effort dev polling; ignore transient fetch errors */
      }
    };

    const watcher = window.setInterval(() => {
      void pollForWasmChanges();
    }, 3000);

    return () => {
      window.clearInterval(watcher);
    };
  }, []);

  useEffect(() => {
    if (window.location.hostname === "app.example") {
      setStatus("error");
      setError(
        "WASM engine metadata is unavailable on this host. Serve /wasm/engine.version.json before booting the viewport."
      );
      return;
    }

    let canceled = false;

    const loadEngineVersion = async () => {
      try {
        const response = await fetch(`/wasm/engine.version.json?meta=${Date.now()}`, {
          cache: "no-store",
        });
        if (!response.ok) {
          if (!canceled) {
            setStatus("error");
            setError(
              `Missing WASM metadata (HTTP ${response.status}). Run asset preparation so /wasm/engine.version.json is published.`
            );
          }
          return;
        }
        const payload = (await response.json()) as { engineAssetVersion?: string };
        if (!canceled && payload.engineAssetVersion) {
          setEngineAssetVersion(payload.engineAssetVersion);
        } else if (!canceled) {
          setStatus("error");
          setError(
            "Invalid WASM metadata payload: engineAssetVersion is required in /wasm/engine.version.json."
          );
        }
      } catch (err) {
        if (!canceled) {
          setStatus("error");
          setError(
            err instanceof Error
              ? `Failed to read WASM metadata: ${err.message}`
              : "Failed to read WASM metadata."
          );
        }
      }
    };

    void loadEngineVersion();
    return () => {
      canceled = true;
    };
  }, []);

  /* C/WASM engine handles all asset rendering */

  const runContextAction = (actionId: string) => {
    const mod = moduleRef.current;
    const svc = uiServiceRef.current;
    if (!mod || !svc) {
      setInteractionMessage("Action unavailable: engine not ready.");
      if (svc) svc.closeContextMenu();
      return;
    }

    const interactionMgr = svc.getInteractionManager();
    const menuState = interactionMgr.getMenuState();

    const result = Number(
      mod.ccall(
        "engine_handle_right_click_normalized",
        "number",
        ["number", "number"],
        [menuState.normalizedX, menuState.normalizedY]
      )
    );

    if (result === 1) {
      setInteractionMessage(`${actionId}: applied to nearest actor.`);
    } else {
      setInteractionMessage(`${actionId}: no target in range.`);
    }
    svc.closeContextMenu();
  };

  useEffect(() => {
    if (engineAssetVersion === "pending") return;

    const canvas = canvasRef.current;
    const viewport = viewportRef.current;
    if (!canvas || !viewport) return;

    const hasPreloadedEngineFactory = typeof window.BananaEngine === "function";
    if (!hasPreloadedEngineFactory && !isWebGL2Available()) {
      setStatus("error");
      setError(
        "WebGL2 context creation failed before engine boot. Enable hardware acceleration or run on a WebGL2-capable runtime."
      );
      return;
    }

    setStatus("loading");

    const startEngine = async () => {
      if (!window.BananaEngine) {
        setStatus("error");
        setError("BananaEngine factory not found after script load");
        return;
      }

      /* Phase 2 Integration: Create GameEngineUIService (manages all UI state) */
      const uiService = new GameEngineUIService(viewport, CONTEXT_MENU_ACTIONS);
      uiServiceRef.current = uiService;

      // Phase 3: initialize multiplayer-ready domains behind the existing UI service.
      if (!netcodeRef.current) {
        netcodeRef.current = new NetcodeDomain(
          { tickRate: 30, maxPrediction: 60 },
          uiService.getInputAggregator(),
          uiService.getInteractionManager()
        );
      }
      if (!replicationRef.current) {
        replicationRef.current = new ReplicationDomain({ maxHistory: 120 });
      }

      /* Subscribe to state changes from service */
      const unsubscribeStateChanges = uiService.onStateChange((uiState: GameEngineUIState) => {
        setStatus(uiState.engineStatus);
        setError(uiState.error ?? null);

        /* Update context menu state from interaction manager */
        const interactionMgr = uiService.getInteractionManager();
        const menuState = interactionMgr.getMenuState();
        setContextMenu(menuState);

        /* Update interaction message from service */
        setInteractionMessage(uiState.interactionMessage ?? null);
      });

      /* Register action handlers with interaction domain */
      const interactionMgr = uiService.getInteractionManager();
      interactionMgr.registerActionHandler("interact", (actionId, normalizedX, normalizedY) => {
        const mod = moduleRef.current;
        if (!mod) {
          return {
            actionId,
            targetNormalizedX: normalizedX,
            targetNormalizedY: normalizedY,
            success: false,
            message: "Engine not ready",
            timestamp: Date.now(),
          };
        }
        const result = Number(
          mod.ccall(
            "engine_handle_right_click_normalized",
            "number",
            ["number", "number"],
            [normalizedX, normalizedY]
          )
        );
        return {
          actionId,
          targetNormalizedX: normalizedX,
          targetNormalizedY: normalizedY,
          success: result === 1,
          message:
            result === 1 ? "Interact: applied to nearest actor." : "Interact: no target in range.",
          timestamp: Date.now(),
        };
      });

      interactionMgr.registerActionHandler("harvest", (actionId, normalizedX, normalizedY) => {
        const mod = moduleRef.current;
        if (!mod) {
          return {
            actionId,
            targetNormalizedX: normalizedX,
            targetNormalizedY: normalizedY,
            success: false,
            message: "Engine not ready",
            timestamp: Date.now(),
          };
        }
        const result = Number(
          mod.ccall(
            "engine_handle_right_click_normalized",
            "number",
            ["number", "number"],
            [normalizedX, normalizedY]
          )
        );
        return {
          actionId,
          targetNormalizedX: normalizedX,
          targetNormalizedY: normalizedY,
          success: result === 1,
          message:
            result === 1 ? "Harvest: applied to nearest actor." : "Harvest: no target in range.",
          timestamp: Date.now(),
        };
      });

      let runtimeInitFailed = false;
      const applyRuntimeFatal = (rawMessage: string) => {
        const message = (rawMessage || "").toLowerCase();
        if (!message) return;
        const isFatalInit =
          message.includes("webgl2 context creation failed") ||
          message.includes("window_create failed") ||
          message.includes("engine_init failed") ||
          message.includes("abort");
        if (!isFatalInit) return;
        runtimeInitFailed = true;
        window.clearInterval(intervalRef.current);
        window.clearTimeout(renderHealthTimerRef.current);
        uiService.setEngineStatus(
          "error",
          "WebGL viewport initialization failed during engine boot. Resolve runtime GPU/WebGL issues and reload."
        );
      };

      try {
        const mod = await window.BananaEngine({
          canvas,
          locateFile: (path, prefix) => `${prefix}${path}?v=${engineAssetVersion}`,
          printErr: (text) => {
            applyRuntimeFatal(text);
          },
          onAbort: (reason) => {
            applyRuntimeFatal(reason);
          },
        });

        if (runtimeInitFailed) {
          unsubscribeStateChanges();
          return;
        }

        moduleRef.current = mod;
        window.__bananaEngineModule = mod;

        /* Event handlers delegate to GameEngineUIService domains */
        const inputMgr = uiService.getInputAggregator();
        const _viewportMgr = uiService.getViewportSizer();

        const keyDown = (event: KeyboardEvent) => {
          const key = event.key.toLowerCase();
          if (key === "escape") {
            uiService.closeContextMenu();
            return;
          }
          if (isMovementKey(key)) {
            inputMgr.updateKeyState(key, true);
            event.preventDefault();
            uiService.closeContextMenu();
          }
        };

        const keyUp = (event: KeyboardEvent) => {
          const key = event.key.toLowerCase();
          if (isMovementKey(key)) {
            inputMgr.updateKeyState(key, false);
          }
        };

        const clearMovementIntent = () => {
          inputMgr.updateKeyState("w", false);
          inputMgr.updateKeyState("a", false);
          inputMgr.updateKeyState("s", false);
          inputMgr.updateKeyState("d", false);
          inputMgr.updateRadialDirection(null);
          mod.ccall("engine_set_move_input", "null", ["number", "number"], [0, 0]);
          setRadialControl({ visible: false, x: 0, y: 0, activeDirection: null });
        };

        const onBlur = () => {
          clearMovementIntent();
        };

        const onVisibilityChange = () => {
          if (document.hidden) {
            clearMovementIntent();
          }
        };

        /* Touch handlers for mobile radial movement control */
        const onTouchStart = (event: TouchEvent) => {
          if (event.touches.length === 0) return;

          const touch = event.touches[0];
          activeTouchIdRef.current = touch.identifier;

          const bounds = viewport.getBoundingClientRect();
          const touchX = bounds ? touch.clientX - bounds.left : touch.clientX;
          const touchY = bounds ? touch.clientY - bounds.top : touch.clientY;

          touchStartTimerRef.current = window.setTimeout(() => {
            setRadialControl({
              visible: true,
              x: touchX,
              y: touchY,
              activeDirection: null,
            });
          }, 150);
        };

        const onTouchMove = (event: TouchEvent) => {
          if (activeTouchIdRef.current === null) return;

          const touch = Array.from(event.touches).find(
            (t) => t.identifier === activeTouchIdRef.current
          );
          if (!touch) return;

          const bounds = viewport.getBoundingClientRect();
          const touchX = bounds ? touch.clientX - bounds.left : touch.clientX;
          const touchY = bounds ? touch.clientY - bounds.top : touch.clientY;

          setRadialControl((prev) => {
            if (!prev.visible) return prev;

            const direction = getDirectionFromTouch(touchX, touchY, prev.x, prev.y);

            if (direction !== prev.activeDirection) {
              inputMgr.updateRadialDirection(direction);
            }

            return { ...prev, activeDirection: direction };
          });
        };

        const onTouchEnd = (event: TouchEvent) => {
          const touch = Array.from(event.changedTouches).find(
            (t) => t.identifier === activeTouchIdRef.current
          );
          if (!touch) return;

          window.clearTimeout(touchStartTimerRef.current);
          activeTouchIdRef.current = null;
          inputMgr.updateRadialDirection(null);
          setRadialControl({ visible: false, x: 0, y: 0, activeDirection: null });
        };

        const onPointerDown = (event: PointerEvent) => {
          if (event.pointerType === "mouse") return;

          activePointerIdRef.current = event.pointerId;

          const bounds = viewport.getBoundingClientRect();
          const touchX = bounds ? event.clientX - bounds.left : event.clientX;
          const touchY = bounds ? event.clientY - bounds.top : event.clientY;

          window.clearTimeout(touchStartTimerRef.current);
          touchStartTimerRef.current = window.setTimeout(() => {
            setRadialControl({
              visible: true,
              x: touchX,
              y: touchY,
              activeDirection: null,
            });
          }, 150);
        };

        const onPointerMove = (event: PointerEvent) => {
          if (activePointerIdRef.current !== event.pointerId) return;

          const bounds = viewport.getBoundingClientRect();
          const touchX = bounds ? event.clientX - bounds.left : event.clientX;
          const touchY = bounds ? event.clientY - bounds.top : event.clientY;

          setRadialControl((prev) => {
            if (!prev.visible) return prev;

            const direction = getDirectionFromTouch(touchX, touchY, prev.x, prev.y);

            if (direction !== prev.activeDirection) {
              inputMgr.updateRadialDirection(direction);
            }

            return { ...prev, activeDirection: direction };
          });
        };

        const onPointerUp = (event: PointerEvent) => {
          if (activePointerIdRef.current !== event.pointerId) return;

          window.clearTimeout(touchStartTimerRef.current);
          activePointerIdRef.current = null;
          inputMgr.updateRadialDirection(null);
          setRadialControl({ visible: false, x: 0, y: 0, activeDirection: null });
        };

        keyDownHandlerRef.current = keyDown;
        keyUpHandlerRef.current = keyUp;
        blurHandlerRef.current = onBlur;
        visibilityHandlerRef.current = onVisibilityChange;
        touchStartHandlerRef.current = onTouchStart;
        touchMoveHandlerRef.current = onTouchMove;
        touchEndHandlerRef.current = onTouchEnd;
        pointerDownHandlerRef.current = onPointerDown;
        pointerMoveHandlerRef.current = onPointerMove;
        pointerUpHandlerRef.current = onPointerUp;

        window.addEventListener("keydown", keyDown, { capture: true });
        window.addEventListener("keyup", keyUp, { capture: true });
        window.addEventListener("blur", onBlur);
        document.addEventListener("visibilitychange", onVisibilityChange);
        window.addEventListener("touchstart", onTouchStart, { passive: true });
        window.addEventListener("touchmove", onTouchMove, { passive: true });
        window.addEventListener("touchend", onTouchEnd, { passive: true });
        window.addEventListener("pointerdown", onPointerDown, { passive: true });
        window.addEventListener("pointermove", onPointerMove, { passive: true });
        window.addEventListener("pointerup", onPointerUp, { passive: true });
        window.addEventListener("pointercancel", onPointerUp, { passive: true });

        uiService.setEngineStatus("running");

        let tickCounter = 0;
        const probeFramebuffer = () => {
          try {
            const gl = canvas.getContext("webgl2");
            if (!gl) {
              applyRuntimeFatal("webgl2 context creation failed");
              return;
            }
            if (gl.isContextLost()) {
              applyRuntimeFatal("webgl2 context creation failed");
            }
          } catch {
            applyRuntimeFatal("webgl2 context creation failed");
          }
        };

        const fpsLoop = () => {
          try {
            /* Get current movement input from service */
            const movement = inputMgr.computeMovement();
            netcodeRef.current?.advanceTick();
            const tick = netcodeRef.current?.getCurrentTick() ?? 0;
            replicationRef.current?.recordState(tick, {
              tick,
              timestamp: Date.now(),
              entities: {
                localPlayer: {
                  moveX: movement.moveX,
                  moveZ: movement.moveZ,
                  source: movement.source,
                },
              },
              isAuthoritative: false,
            });
            mod.ccall(
              "engine_set_move_input",
              "null",
              ["number", "number"],
              [movement.moveX, movement.moveZ]
            );
            mod.ccall("engine_tick", "number", ["number"], [1 / 60]);
            tickCounter += 1;
            if (tickCounter % 60 === 0) {
              probeFramebuffer();
            }
          } catch {
            uiService.setEngineStatus(
              "error",
              "Engine runtime failed while rendering. Reload the page or run on a browser/device with working WebGL2."
            );
            window.clearInterval(intervalRef.current);
          }
        };

        intervalRef.current = window.setInterval(fpsLoop, 16);

        renderHealthTimerRef.current = window.setTimeout(() => {
          if (runtimeInitFailed) return;
          probeFramebuffer();
        }, 1200);
      } catch (e) {
        uiService.setEngineStatus(
          "error",
          e instanceof Error ? e.message : "Engine initialization failed"
        );
        unsubscribeStateChanges();
      }
    };

    if (typeof window.BananaEngine === "function") {
      void startEngine();
    } else {
      const script = document.createElement("script");
      script.src = `/wasm/engine.js?v=${engineAssetVersion}`;
      scriptRef.current = script;

      script.onerror = () => {
        setStatus("unavailable");
        setError(
          "engine.js not found. Run: bash scripts/build-engine-wasm.sh (requires Emscripten SDK)"
        );
      };

      script.onload = () => {
        void startEngine();
      };

      document.head.appendChild(script);
    }

    return () => {
      window.clearInterval(intervalRef.current);
      window.clearTimeout(touchStartTimerRef.current);
      window.clearTimeout(renderHealthTimerRef.current);

      if (keyDownHandlerRef.current) {
        window.removeEventListener("keydown", keyDownHandlerRef.current, { capture: true });
        keyDownHandlerRef.current = null;
      }
      if (keyUpHandlerRef.current) {
        window.removeEventListener("keyup", keyUpHandlerRef.current, { capture: true });
        keyUpHandlerRef.current = null;
      }
      if (blurHandlerRef.current) {
        window.removeEventListener("blur", blurHandlerRef.current);
        blurHandlerRef.current = null;
      }
      if (visibilityHandlerRef.current) {
        document.removeEventListener("visibilitychange", visibilityHandlerRef.current);
        visibilityHandlerRef.current = null;
      }
      if (touchStartHandlerRef.current) {
        window.removeEventListener("touchstart", touchStartHandlerRef.current);
        touchStartHandlerRef.current = null;
      }
      if (touchMoveHandlerRef.current) {
        window.removeEventListener("touchmove", touchMoveHandlerRef.current);
        touchMoveHandlerRef.current = null;
      }
      if (touchEndHandlerRef.current) {
        window.removeEventListener("touchend", touchEndHandlerRef.current);
        touchEndHandlerRef.current = null;
      }
      if (pointerDownHandlerRef.current) {
        window.removeEventListener("pointerdown", pointerDownHandlerRef.current);
        pointerDownHandlerRef.current = null;
      }
      if (pointerMoveHandlerRef.current) {
        window.removeEventListener("pointermove", pointerMoveHandlerRef.current);
        pointerMoveHandlerRef.current = null;
      }
      if (pointerUpHandlerRef.current) {
        window.removeEventListener("pointerup", pointerUpHandlerRef.current);
        window.removeEventListener("pointercancel", pointerUpHandlerRef.current);
        pointerUpHandlerRef.current = null;
      }

      scriptRef.current?.remove();
      delete window.__bananaEngineModule;
      moduleRef.current = null;
      uiServiceRef.current = null;
      netcodeRef.current = null;
      replicationRef.current = null;
    };
  }, [engineAssetVersion]);

  const showSplash = status === "idle" || status === "loading";

  return (
    <div
      ref={viewportRef}
      style={{
        position: "fixed",
        inset: 0,
        width: "100vw",
        height: "100vh",
        minHeight: "100dvh",
        margin: 0,
        padding: 0,
        overflow: "hidden",
        backgroundColor: "#000",
        touchAction: "none",
      }}
    >
      <SplashOverlay visible={showSplash} />

      {/* biome-ignore lint: useUniqueElementIds */}
      {/* Primary WASM viewport — 100% coverage, responsive sizing handled by C engine */}
      <canvas
        id="canvas"
        ref={canvasRef}
        onMouseDown={() => {
          if (contextMenu.visible) {
            const svc = uiServiceRef.current;
            if (svc) svc.closeContextMenu();
          }
        }}
        onContextMenu={(event) => {
          event.preventDefault();
          const svc = uiServiceRef.current;
          if (!svc) return;

          const bounds = viewportRef.current?.getBoundingClientRect();
          const relativeX = bounds ? event.clientX - bounds.left : event.clientX;
          const relativeY = bounds ? event.clientY - bounds.top : event.clientY;

          svc.openContextMenu(relativeX, relativeY);
        }}
        style={{
          display: "block",
          width: "100%",
          height: "100%",
          imageRendering: "pixelated",
          touchAction: "none",
        }}
      />

      {/* Error overlay */}
      {(status === "error" || status === "unavailable") && error && (
        <ViewportErrorOverlay error={error} onReload={() => window.location.reload()} />
      )}

      {/* Error notification badge */}
      {(status === "error" || status === "unavailable") && error && <ErrorBadge message={error} />}

      {/* Controls hint */}
      <ControlsHint />

      {/* Context menu */}
      <ContextMenu
        state={contextMenu}
        actions={CONTEXT_MENU_ACTIONS}
        onAction={runContextAction}
        onClose={() => setContextMenu((prev) => ({ ...prev, visible: false }))}
      />

      {/* Mobile radial control */}
      <MobileRadialControl state={radialControl} />

      {/* Interaction message badge */}
      {interactionMessage && <InteractionMessageBadge message={interactionMessage} />}

      {/* Engine version debug badge */}
      <EngineVersionBadge version={engineAssetVersion} messagePresent={!!interactionMessage} />
    </div>
  );
}
