// Slice 026 -- generates `src/tokens/web.css` from `src/tokens/index.ts`.
// Idempotent: re-running with no source change leaves the file untouched.
// Run via `bun run tokens:gen` from `src/typescript/shared/ui`.

import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

import {tokens} from '../src/tokens/index.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '..', 'src', 'tokens', 'web.css');

type Primitive = string|number;
type Nested = {
  [key: string]: Primitive|Nested
};

function toCssVarName(path: string[]): string {
  return '--' +
      path.map((p) => p.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase()))
          .join('-');
}

function formatValue(value: Primitive, path: string[]): string {
  if (typeof value === 'number') {
    // Spacing / radius / font-size are unit-less in tokens.ts; emit px
    // for the web side. Motion already carries its unit (ms) as a string.
    return `${value}px`;
  }
  return String(value);
}

function flatten(
    obj: Nested, prefix: string[] = [], out: string[] = []): string[] {
  for (const [k, v] of Object.entries(obj)) {
    const next = [...prefix, k];
    if (v !== null && typeof v === 'object') {
      flatten(v as Nested, next, out);
    } else {
      out.push(
          `  ${toCssVarName(next)}: ${formatValue(v as Primitive, next)};`);
    }
  }
  return out;
}

const banner =
    '/* Generated by scripts/generate-web-tokens.ts. Do not edit by hand. */\n' +
    '/* Source: src/tokens/index.ts -- run `bun run tokens:gen` to regenerate. */\n';

const css = banner + ':root {\n' +
    flatten(tokens as unknown as Nested).join('\n') + '\n}\n';

const existing = existsSync(outPath) ? readFileSync(outPath, 'utf8') : null;
if (existing === css) {
  console.log('[tokens:gen] web.css already up to date');
} else {
  writeFileSync(outPath, css, 'utf8');
  console.log(`[tokens:gen] wrote ${outPath}`);
}
