directories:
  output: ../../../artifacts/steam-build/dev-candidate
  buildResources: build
appId: com.banana.engineer
productName: BananaEngineer
files:
  - filter:
      - main.js
      - package.json
asar: true
win:
  target:
    - dir
  artifactName: BananaEngineer-${version}-${arch}.${ext}
electronVersion: 31.7.7
